modLoader="javafml"
loaderVersion="[4,)"
license="All Rights Reserved"

[[mods]]
modId="remnant_bosses"
version="1.2.0"
displayName="Remnant Bosses"
displayURL="https://meherbensalem.github.io"
logoFile="logo.png"
credits="no credits"
authors="NAIZO"
description="Face the deadliest skeletal entity ever forged combat, fights, and chaos await!"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.remnant_bosses]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.65,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.remnant_bosses]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="AFTER"
    side="BOTH"

[[dependencies.remnant_bosses]]
    modId="geckolib"
    type="required"
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.remnant_bosses]]
    modId="jauml"
    type="required"
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.remnant_bosses]]
    modId="geckolib"
    type="optional"
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.remnant_bosses]]
    modId="jauml"
    type="optional"
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration